SET(WILDMAGIC_HOME $ENV{WM4_PATH})

IF(WILDMAGIC_HOME)

    SET(WILDMAGIC_LIBRARIES_DIR ${WILDMAGIC_HOME}/SDK/Library/${CMAKE_BUILD_TYPE})
    
    FIND_PATH(WILDMAGIC_INCLUDE_DIR Wm4System.h ${WILDMAGIC_HOME}/SDK/Include)
    FIND_LIBRARY(WILDMAGIC_LIBRARIES NAMES Wm4Foundation Wm4Graphics Wm4Imagics PATHS ${WILDMAGIC_LIBRARIES_DIR})

    IF (WILDMAGIC_INCLUDE_DIR AND WILDMAGIC_LIBRARIES)
       SET(WILDMAGIC_FOUND TRUE)
    ENDIF (WILDMAGIC_INCLUDE_DIR AND WILDMAGIC_LIBRARIES)
    
ENDIF(WILDMAGIC_HOME)

IF(WILDMAGIC_FOUND)

   IF(NOT WildMagic4_FIND_QUIETLY)
      MESSAGE(STATUS "Found WildMagic4: ${WILDMAGIC_LIBRARIES}")
   ENDIF(NOT WildMagic4_FIND_QUIETLY)
   
ELSE(WILDMAGIC_FOUND)

   IF(WildMagic4_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find WildMagic4 ( Environment variable WM4_PATH not set ? )")
   ENDIF(WildMagic4_FIND_REQUIRED)
   
ENDIF(WILDMAGIC_FOUND)
